[build]
builder = "nixpacks"
buildCommand = "npm run build:railway"

[deploy]
startCommand = "npm run start:railway"
healthcheckPath = "/health/ping"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
healthcheckInterval = 15

[environments]
NODE_ENV = "production"
PORT = "8080" 