services:
  - type: web
    name: api
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && bash render-build.sh
    startCommand: cd backend && node dist/main.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        fromDatabase:
          name: nionfar-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 3600
      - key: REFRESH_TOKEN_EXPIRATION
        value: 604800

databases:
  - name: nionfar-db
    region: frankfurt
    plan: free
    ipAllowList: [] 