"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.User = exports.UserStatus = void 0;
const typeorm_1 = require("typeorm");
const class_transformer_1 = require("class-transformer");
const user_role_enum_1 = require("../enums/user-role.enum");
const service_entity_1 = require("../../services/entities/service.entity");
const order_entity_1 = require("../../orders/entities/order.entity");
const review_entity_1 = require("../../reviews/entities/review.entity");
const message_entity_1 = require("../../messages/entities/message.entity");
var UserStatus;
(function (UserStatus) {
    UserStatus["ACTIVE"] = "active";
    UserStatus["INACTIVE"] = "inactive";
    UserStatus["SUSPENDED"] = "suspended";
    UserStatus["PENDING_VERIFICATION"] = "pending_verification";
})(UserStatus || (exports.UserStatus = UserStatus = {}));
let User = (() => {
    let _classDecorators = [(0, typeorm_1.Entity)('users')];
    let _classDescriptor;
    let _classExtraInitializers = [];
    let _classThis;
    let _id_decorators;
    let _id_initializers = [];
    let _id_extraInitializers = [];
    let _email_decorators;
    let _email_initializers = [];
    let _email_extraInitializers = [];
    let _firstName_decorators;
    let _firstName_initializers = [];
    let _firstName_extraInitializers = [];
    let _lastName_decorators;
    let _lastName_initializers = [];
    let _lastName_extraInitializers = [];
    let _username_decorators;
    let _username_initializers = [];
    let _username_extraInitializers = [];
    let _password_decorators;
    let _password_initializers = [];
    let _password_extraInitializers = [];
    let _role_decorators;
    let _role_initializers = [];
    let _role_extraInitializers = [];
    let _status_decorators;
    let _status_initializers = [];
    let _status_extraInitializers = [];
    let _phone_decorators;
    let _phone_initializers = [];
    let _phone_extraInitializers = [];
    let _address_decorators;
    let _address_initializers = [];
    let _address_extraInitializers = [];
    let _city_decorators;
    let _city_initializers = [];
    let _city_extraInitializers = [];
    let _country_decorators;
    let _country_initializers = [];
    let _country_extraInitializers = [];
    let _bio_decorators;
    let _bio_initializers = [];
    let _bio_extraInitializers = [];
    let _skills_decorators;
    let _skills_initializers = [];
    let _skills_extraInitializers = [];
    let _isEmailVerified_decorators;
    let _isEmailVerified_initializers = [];
    let _isEmailVerified_extraInitializers = [];
    let _isPhoneVerified_decorators;
    let _isPhoneVerified_initializers = [];
    let _isPhoneVerified_extraInitializers = [];
    let _isIdentityVerified_decorators;
    let _isIdentityVerified_initializers = [];
    let _isIdentityVerified_extraInitializers = [];
    let _memberSince_decorators;
    let _memberSince_initializers = [];
    let _memberSince_extraInitializers = [];
    let _providerProfile_decorators;
    let _providerProfile_initializers = [];
    let _providerProfile_extraInitializers = [];
    let _completedOrders_decorators;
    let _completedOrders_initializers = [];
    let _completedOrders_extraInitializers = [];
    let _rating_decorators;
    let _rating_initializers = [];
    let _rating_extraInitializers = [];
    let _totalReviews_decorators;
    let _totalReviews_initializers = [];
    let _totalReviews_extraInitializers = [];
    let _paymentInfo_decorators;
    let _paymentInfo_initializers = [];
    let _paymentInfo_extraInitializers = [];
    let _notificationPreferences_decorators;
    let _notificationPreferences_initializers = [];
    let _notificationPreferences_extraInitializers = [];
    let _phoneNumber_decorators;
    let _phoneNumber_initializers = [];
    let _phoneNumber_extraInitializers = [];
    let _isTwoFactorEnabled_decorators;
    let _isTwoFactorEnabled_initializers = [];
    let _isTwoFactorEnabled_extraInitializers = [];
    let _twoFactorSecret_decorators;
    let _twoFactorSecret_initializers = [];
    let _twoFactorSecret_extraInitializers = [];
    let _avatar_decorators;
    let _avatar_initializers = [];
    let _avatar_extraInitializers = [];
    let _bioText_decorators;
    let _bioText_initializers = [];
    let _bioText_extraInitializers = [];
    let _balance_decorators;
    let _balance_initializers = [];
    let _balance_extraInitializers = [];
    let _isFreelancer_decorators;
    let _isFreelancer_initializers = [];
    let _isFreelancer_extraInitializers = [];
    let _isActive_decorators;
    let _isActive_initializers = [];
    let _isActive_extraInitializers = [];
    let _lastLogin_decorators;
    let _lastLogin_initializers = [];
    let _lastLogin_extraInitializers = [];
    let _refreshToken_decorators;
    let _refreshToken_initializers = [];
    let _refreshToken_extraInitializers = [];
    let _resetPasswordToken_decorators;
    let _resetPasswordToken_initializers = [];
    let _resetPasswordToken_extraInitializers = [];
    let _resetPasswordExpires_decorators;
    let _resetPasswordExpires_initializers = [];
    let _resetPasswordExpires_extraInitializers = [];
    let _emailVerificationToken_decorators;
    let _emailVerificationToken_initializers = [];
    let _emailVerificationToken_extraInitializers = [];
    let _services_decorators;
    let _services_initializers = [];
    let _services_extraInitializers = [];
    let _clientOrders_decorators;
    let _clientOrders_initializers = [];
    let _clientOrders_extraInitializers = [];
    let _freelancerOrders_decorators;
    let _freelancerOrders_initializers = [];
    let _freelancerOrders_extraInitializers = [];
    let _givenReviews_decorators;
    let _givenReviews_initializers = [];
    let _givenReviews_extraInitializers = [];
    let _receivedReviews_decorators;
    let _receivedReviews_initializers = [];
    let _receivedReviews_extraInitializers = [];
    let _sentMessages_decorators;
    let _sentMessages_initializers = [];
    let _sentMessages_extraInitializers = [];
    let _receivedMessages_decorators;
    let _receivedMessages_initializers = [];
    let _receivedMessages_extraInitializers = [];
    let _following_decorators;
    let _following_initializers = [];
    let _following_extraInitializers = [];
    let _followers_decorators;
    let _followers_initializers = [];
    let _followers_extraInitializers = [];
    let _createdAt_decorators;
    let _createdAt_initializers = [];
    let _createdAt_extraInitializers = [];
    let _updatedAt_decorators;
    let _updatedAt_initializers = [];
    let _updatedAt_extraInitializers = [];
    var User = class {
        static { _classThis = this; }
        static {
            const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
            _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
            _email_decorators = [(0, typeorm_1.Column)({ unique: true })];
            _firstName_decorators = [(0, typeorm_1.Column)({ length: 100 })];
            _lastName_decorators = [(0, typeorm_1.Column)({ length: 100 })];
            _username_decorators = [(0, typeorm_1.Column)({ unique: true, nullable: true })];
            _password_decorators = [(0, typeorm_1.Column)({ select: false })];
            _role_decorators = [(0, typeorm_1.Column)({
                    type: 'enum',
                    enum: user_role_enum_1.UserRole,
                    default: user_role_enum_1.UserRole.CLIENT
                })];
            _status_decorators = [(0, typeorm_1.Column)({
                    type: 'enum',
                    enum: UserStatus,
                    default: UserStatus.PENDING_VERIFICATION
                })];
            _phone_decorators = [(0, typeorm_1.Column)({ nullable: true })];
            _address_decorators = [(0, typeorm_1.Column)({ nullable: true })];
            _city_decorators = [(0, typeorm_1.Column)({ nullable: true })];
            _country_decorators = [(0, typeorm_1.Column)({ nullable: true })];
            _bio_decorators = [(0, typeorm_1.Column)({ nullable: true })];
            _skills_decorators = [(0, typeorm_1.Column)('simple-array', { nullable: true })];
            _isEmailVerified_decorators = [(0, typeorm_1.Column)({ default: false })];
            _isPhoneVerified_decorators = [(0, typeorm_1.Column)({ default: false })];
            _isIdentityVerified_decorators = [(0, typeorm_1.Column)({ default: false })];
            _memberSince_decorators = [(0, typeorm_1.Column)({ nullable: true })];
            _providerProfile_decorators = [(0, typeorm_1.Column)({ type: 'json', nullable: true })];
            _completedOrders_decorators = [(0, typeorm_1.Column)({ default: 0 })];
            _rating_decorators = [(0, typeorm_1.Column)({ default: 0, type: 'decimal', precision: 3, scale: 2 })];
            _totalReviews_decorators = [(0, typeorm_1.Column)({ default: 0 })];
            _paymentInfo_decorators = [(0, typeorm_1.Column)({ type: 'json', nullable: true })];
            _notificationPreferences_decorators = [(0, typeorm_1.Column)({ type: 'json', nullable: true })];
            _phoneNumber_decorators = [(0, typeorm_1.Column)({ nullable: true })];
            _isTwoFactorEnabled_decorators = [(0, typeorm_1.Column)({ default: false })];
            _twoFactorSecret_decorators = [(0, typeorm_1.Column)({ nullable: true }), (0, class_transformer_1.Exclude)()];
            _avatar_decorators = [(0, typeorm_1.Column)({ nullable: true })];
            _bioText_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
            _balance_decorators = [(0, typeorm_1.Column)({ default: 0 })];
            _isFreelancer_decorators = [(0, typeorm_1.Column)({ default: false })];
            _isActive_decorators = [(0, typeorm_1.Column)({ default: true })];
            _lastLogin_decorators = [(0, typeorm_1.Column)({ nullable: true })];
            _refreshToken_decorators = [(0, typeorm_1.Column)({ nullable: true })];
            _resetPasswordToken_decorators = [(0, typeorm_1.Column)({ nullable: true }), (0, class_transformer_1.Exclude)()];
            _resetPasswordExpires_decorators = [(0, typeorm_1.Column)({ nullable: true })];
            _emailVerificationToken_decorators = [(0, typeorm_1.Column)({ nullable: true }), (0, class_transformer_1.Exclude)()];
            _services_decorators = [(0, typeorm_1.OneToMany)(() => service_entity_1.Service, (service) => service.provider)];
            _clientOrders_decorators = [(0, typeorm_1.OneToMany)(() => order_entity_1.Order, (order) => order.client)];
            _freelancerOrders_decorators = [(0, typeorm_1.OneToMany)(() => order_entity_1.Order, (order) => order.freelancer)];
            _givenReviews_decorators = [(0, typeorm_1.OneToMany)(() => review_entity_1.Review, (review) => review.reviewer)];
            _receivedReviews_decorators = [(0, typeorm_1.OneToMany)(() => review_entity_1.Review, (review) => review.reviewee)];
            _sentMessages_decorators = [(0, typeorm_1.OneToMany)(() => message_entity_1.Message, (message) => message.sender)];
            _receivedMessages_decorators = [(0, typeorm_1.OneToMany)(() => message_entity_1.Message, (message) => message.receiver)];
            _following_decorators = [(0, typeorm_1.ManyToMany)(() => User), (0, typeorm_1.JoinTable)({
                    name: 'user_followers',
                    joinColumn: { name: 'followerId', referencedColumnName: 'id' },
                    inverseJoinColumn: { name: 'followingId', referencedColumnName: 'id' },
                })];
            _followers_decorators = [(0, typeorm_1.ManyToMany)(() => User), (0, typeorm_1.JoinTable)({
                    name: 'user_followers',
                    joinColumn: { name: 'followingId', referencedColumnName: 'id' },
                    inverseJoinColumn: { name: 'followerId', referencedColumnName: 'id' },
                })];
            _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)()];
            _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)()];
            __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: obj => "id" in obj, get: obj => obj.id, set: (obj, value) => { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
            __esDecorate(null, null, _email_decorators, { kind: "field", name: "email", static: false, private: false, access: { has: obj => "email" in obj, get: obj => obj.email, set: (obj, value) => { obj.email = value; } }, metadata: _metadata }, _email_initializers, _email_extraInitializers);
            __esDecorate(null, null, _firstName_decorators, { kind: "field", name: "firstName", static: false, private: false, access: { has: obj => "firstName" in obj, get: obj => obj.firstName, set: (obj, value) => { obj.firstName = value; } }, metadata: _metadata }, _firstName_initializers, _firstName_extraInitializers);
            __esDecorate(null, null, _lastName_decorators, { kind: "field", name: "lastName", static: false, private: false, access: { has: obj => "lastName" in obj, get: obj => obj.lastName, set: (obj, value) => { obj.lastName = value; } }, metadata: _metadata }, _lastName_initializers, _lastName_extraInitializers);
            __esDecorate(null, null, _username_decorators, { kind: "field", name: "username", static: false, private: false, access: { has: obj => "username" in obj, get: obj => obj.username, set: (obj, value) => { obj.username = value; } }, metadata: _metadata }, _username_initializers, _username_extraInitializers);
            __esDecorate(null, null, _password_decorators, { kind: "field", name: "password", static: false, private: false, access: { has: obj => "password" in obj, get: obj => obj.password, set: (obj, value) => { obj.password = value; } }, metadata: _metadata }, _password_initializers, _password_extraInitializers);
            __esDecorate(null, null, _role_decorators, { kind: "field", name: "role", static: false, private: false, access: { has: obj => "role" in obj, get: obj => obj.role, set: (obj, value) => { obj.role = value; } }, metadata: _metadata }, _role_initializers, _role_extraInitializers);
            __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: obj => "status" in obj, get: obj => obj.status, set: (obj, value) => { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
            __esDecorate(null, null, _phone_decorators, { kind: "field", name: "phone", static: false, private: false, access: { has: obj => "phone" in obj, get: obj => obj.phone, set: (obj, value) => { obj.phone = value; } }, metadata: _metadata }, _phone_initializers, _phone_extraInitializers);
            __esDecorate(null, null, _address_decorators, { kind: "field", name: "address", static: false, private: false, access: { has: obj => "address" in obj, get: obj => obj.address, set: (obj, value) => { obj.address = value; } }, metadata: _metadata }, _address_initializers, _address_extraInitializers);
            __esDecorate(null, null, _city_decorators, { kind: "field", name: "city", static: false, private: false, access: { has: obj => "city" in obj, get: obj => obj.city, set: (obj, value) => { obj.city = value; } }, metadata: _metadata }, _city_initializers, _city_extraInitializers);
            __esDecorate(null, null, _country_decorators, { kind: "field", name: "country", static: false, private: false, access: { has: obj => "country" in obj, get: obj => obj.country, set: (obj, value) => { obj.country = value; } }, metadata: _metadata }, _country_initializers, _country_extraInitializers);
            __esDecorate(null, null, _bio_decorators, { kind: "field", name: "bio", static: false, private: false, access: { has: obj => "bio" in obj, get: obj => obj.bio, set: (obj, value) => { obj.bio = value; } }, metadata: _metadata }, _bio_initializers, _bio_extraInitializers);
            __esDecorate(null, null, _skills_decorators, { kind: "field", name: "skills", static: false, private: false, access: { has: obj => "skills" in obj, get: obj => obj.skills, set: (obj, value) => { obj.skills = value; } }, metadata: _metadata }, _skills_initializers, _skills_extraInitializers);
            __esDecorate(null, null, _isEmailVerified_decorators, { kind: "field", name: "isEmailVerified", static: false, private: false, access: { has: obj => "isEmailVerified" in obj, get: obj => obj.isEmailVerified, set: (obj, value) => { obj.isEmailVerified = value; } }, metadata: _metadata }, _isEmailVerified_initializers, _isEmailVerified_extraInitializers);
            __esDecorate(null, null, _isPhoneVerified_decorators, { kind: "field", name: "isPhoneVerified", static: false, private: false, access: { has: obj => "isPhoneVerified" in obj, get: obj => obj.isPhoneVerified, set: (obj, value) => { obj.isPhoneVerified = value; } }, metadata: _metadata }, _isPhoneVerified_initializers, _isPhoneVerified_extraInitializers);
            __esDecorate(null, null, _isIdentityVerified_decorators, { kind: "field", name: "isIdentityVerified", static: false, private: false, access: { has: obj => "isIdentityVerified" in obj, get: obj => obj.isIdentityVerified, set: (obj, value) => { obj.isIdentityVerified = value; } }, metadata: _metadata }, _isIdentityVerified_initializers, _isIdentityVerified_extraInitializers);
            __esDecorate(null, null, _memberSince_decorators, { kind: "field", name: "memberSince", static: false, private: false, access: { has: obj => "memberSince" in obj, get: obj => obj.memberSince, set: (obj, value) => { obj.memberSince = value; } }, metadata: _metadata }, _memberSince_initializers, _memberSince_extraInitializers);
            __esDecorate(null, null, _providerProfile_decorators, { kind: "field", name: "providerProfile", static: false, private: false, access: { has: obj => "providerProfile" in obj, get: obj => obj.providerProfile, set: (obj, value) => { obj.providerProfile = value; } }, metadata: _metadata }, _providerProfile_initializers, _providerProfile_extraInitializers);
            __esDecorate(null, null, _completedOrders_decorators, { kind: "field", name: "completedOrders", static: false, private: false, access: { has: obj => "completedOrders" in obj, get: obj => obj.completedOrders, set: (obj, value) => { obj.completedOrders = value; } }, metadata: _metadata }, _completedOrders_initializers, _completedOrders_extraInitializers);
            __esDecorate(null, null, _rating_decorators, { kind: "field", name: "rating", static: false, private: false, access: { has: obj => "rating" in obj, get: obj => obj.rating, set: (obj, value) => { obj.rating = value; } }, metadata: _metadata }, _rating_initializers, _rating_extraInitializers);
            __esDecorate(null, null, _totalReviews_decorators, { kind: "field", name: "totalReviews", static: false, private: false, access: { has: obj => "totalReviews" in obj, get: obj => obj.totalReviews, set: (obj, value) => { obj.totalReviews = value; } }, metadata: _metadata }, _totalReviews_initializers, _totalReviews_extraInitializers);
            __esDecorate(null, null, _paymentInfo_decorators, { kind: "field", name: "paymentInfo", static: false, private: false, access: { has: obj => "paymentInfo" in obj, get: obj => obj.paymentInfo, set: (obj, value) => { obj.paymentInfo = value; } }, metadata: _metadata }, _paymentInfo_initializers, _paymentInfo_extraInitializers);
            __esDecorate(null, null, _notificationPreferences_decorators, { kind: "field", name: "notificationPreferences", static: false, private: false, access: { has: obj => "notificationPreferences" in obj, get: obj => obj.notificationPreferences, set: (obj, value) => { obj.notificationPreferences = value; } }, metadata: _metadata }, _notificationPreferences_initializers, _notificationPreferences_extraInitializers);
            __esDecorate(null, null, _phoneNumber_decorators, { kind: "field", name: "phoneNumber", static: false, private: false, access: { has: obj => "phoneNumber" in obj, get: obj => obj.phoneNumber, set: (obj, value) => { obj.phoneNumber = value; } }, metadata: _metadata }, _phoneNumber_initializers, _phoneNumber_extraInitializers);
            __esDecorate(null, null, _isTwoFactorEnabled_decorators, { kind: "field", name: "isTwoFactorEnabled", static: false, private: false, access: { has: obj => "isTwoFactorEnabled" in obj, get: obj => obj.isTwoFactorEnabled, set: (obj, value) => { obj.isTwoFactorEnabled = value; } }, metadata: _metadata }, _isTwoFactorEnabled_initializers, _isTwoFactorEnabled_extraInitializers);
            __esDecorate(null, null, _twoFactorSecret_decorators, { kind: "field", name: "twoFactorSecret", static: false, private: false, access: { has: obj => "twoFactorSecret" in obj, get: obj => obj.twoFactorSecret, set: (obj, value) => { obj.twoFactorSecret = value; } }, metadata: _metadata }, _twoFactorSecret_initializers, _twoFactorSecret_extraInitializers);
            __esDecorate(null, null, _avatar_decorators, { kind: "field", name: "avatar", static: false, private: false, access: { has: obj => "avatar" in obj, get: obj => obj.avatar, set: (obj, value) => { obj.avatar = value; } }, metadata: _metadata }, _avatar_initializers, _avatar_extraInitializers);
            __esDecorate(null, null, _bioText_decorators, { kind: "field", name: "bioText", static: false, private: false, access: { has: obj => "bioText" in obj, get: obj => obj.bioText, set: (obj, value) => { obj.bioText = value; } }, metadata: _metadata }, _bioText_initializers, _bioText_extraInitializers);
            __esDecorate(null, null, _balance_decorators, { kind: "field", name: "balance", static: false, private: false, access: { has: obj => "balance" in obj, get: obj => obj.balance, set: (obj, value) => { obj.balance = value; } }, metadata: _metadata }, _balance_initializers, _balance_extraInitializers);
            __esDecorate(null, null, _isFreelancer_decorators, { kind: "field", name: "isFreelancer", static: false, private: false, access: { has: obj => "isFreelancer" in obj, get: obj => obj.isFreelancer, set: (obj, value) => { obj.isFreelancer = value; } }, metadata: _metadata }, _isFreelancer_initializers, _isFreelancer_extraInitializers);
            __esDecorate(null, null, _isActive_decorators, { kind: "field", name: "isActive", static: false, private: false, access: { has: obj => "isActive" in obj, get: obj => obj.isActive, set: (obj, value) => { obj.isActive = value; } }, metadata: _metadata }, _isActive_initializers, _isActive_extraInitializers);
            __esDecorate(null, null, _lastLogin_decorators, { kind: "field", name: "lastLogin", static: false, private: false, access: { has: obj => "lastLogin" in obj, get: obj => obj.lastLogin, set: (obj, value) => { obj.lastLogin = value; } }, metadata: _metadata }, _lastLogin_initializers, _lastLogin_extraInitializers);
            __esDecorate(null, null, _refreshToken_decorators, { kind: "field", name: "refreshToken", static: false, private: false, access: { has: obj => "refreshToken" in obj, get: obj => obj.refreshToken, set: (obj, value) => { obj.refreshToken = value; } }, metadata: _metadata }, _refreshToken_initializers, _refreshToken_extraInitializers);
            __esDecorate(null, null, _resetPasswordToken_decorators, { kind: "field", name: "resetPasswordToken", static: false, private: false, access: { has: obj => "resetPasswordToken" in obj, get: obj => obj.resetPasswordToken, set: (obj, value) => { obj.resetPasswordToken = value; } }, metadata: _metadata }, _resetPasswordToken_initializers, _resetPasswordToken_extraInitializers);
            __esDecorate(null, null, _resetPasswordExpires_decorators, { kind: "field", name: "resetPasswordExpires", static: false, private: false, access: { has: obj => "resetPasswordExpires" in obj, get: obj => obj.resetPasswordExpires, set: (obj, value) => { obj.resetPasswordExpires = value; } }, metadata: _metadata }, _resetPasswordExpires_initializers, _resetPasswordExpires_extraInitializers);
            __esDecorate(null, null, _emailVerificationToken_decorators, { kind: "field", name: "emailVerificationToken", static: false, private: false, access: { has: obj => "emailVerificationToken" in obj, get: obj => obj.emailVerificationToken, set: (obj, value) => { obj.emailVerificationToken = value; } }, metadata: _metadata }, _emailVerificationToken_initializers, _emailVerificationToken_extraInitializers);
            __esDecorate(null, null, _services_decorators, { kind: "field", name: "services", static: false, private: false, access: { has: obj => "services" in obj, get: obj => obj.services, set: (obj, value) => { obj.services = value; } }, metadata: _metadata }, _services_initializers, _services_extraInitializers);
            __esDecorate(null, null, _clientOrders_decorators, { kind: "field", name: "clientOrders", static: false, private: false, access: { has: obj => "clientOrders" in obj, get: obj => obj.clientOrders, set: (obj, value) => { obj.clientOrders = value; } }, metadata: _metadata }, _clientOrders_initializers, _clientOrders_extraInitializers);
            __esDecorate(null, null, _freelancerOrders_decorators, { kind: "field", name: "freelancerOrders", static: false, private: false, access: { has: obj => "freelancerOrders" in obj, get: obj => obj.freelancerOrders, set: (obj, value) => { obj.freelancerOrders = value; } }, metadata: _metadata }, _freelancerOrders_initializers, _freelancerOrders_extraInitializers);
            __esDecorate(null, null, _givenReviews_decorators, { kind: "field", name: "givenReviews", static: false, private: false, access: { has: obj => "givenReviews" in obj, get: obj => obj.givenReviews, set: (obj, value) => { obj.givenReviews = value; } }, metadata: _metadata }, _givenReviews_initializers, _givenReviews_extraInitializers);
            __esDecorate(null, null, _receivedReviews_decorators, { kind: "field", name: "receivedReviews", static: false, private: false, access: { has: obj => "receivedReviews" in obj, get: obj => obj.receivedReviews, set: (obj, value) => { obj.receivedReviews = value; } }, metadata: _metadata }, _receivedReviews_initializers, _receivedReviews_extraInitializers);
            __esDecorate(null, null, _sentMessages_decorators, { kind: "field", name: "sentMessages", static: false, private: false, access: { has: obj => "sentMessages" in obj, get: obj => obj.sentMessages, set: (obj, value) => { obj.sentMessages = value; } }, metadata: _metadata }, _sentMessages_initializers, _sentMessages_extraInitializers);
            __esDecorate(null, null, _receivedMessages_decorators, { kind: "field", name: "receivedMessages", static: false, private: false, access: { has: obj => "receivedMessages" in obj, get: obj => obj.receivedMessages, set: (obj, value) => { obj.receivedMessages = value; } }, metadata: _metadata }, _receivedMessages_initializers, _receivedMessages_extraInitializers);
            __esDecorate(null, null, _following_decorators, { kind: "field", name: "following", static: false, private: false, access: { has: obj => "following" in obj, get: obj => obj.following, set: (obj, value) => { obj.following = value; } }, metadata: _metadata }, _following_initializers, _following_extraInitializers);
            __esDecorate(null, null, _followers_decorators, { kind: "field", name: "followers", static: false, private: false, access: { has: obj => "followers" in obj, get: obj => obj.followers, set: (obj, value) => { obj.followers = value; } }, metadata: _metadata }, _followers_initializers, _followers_extraInitializers);
            __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: obj => "createdAt" in obj, get: obj => obj.createdAt, set: (obj, value) => { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
            __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: obj => "updatedAt" in obj, get: obj => obj.updatedAt, set: (obj, value) => { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
            __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
            User = _classThis = _classDescriptor.value;
            if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
            __runInitializers(_classThis, _classExtraInitializers);
        }
        id = __runInitializers(this, _id_initializers, void 0);
        email = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _email_initializers, void 0));
        firstName = (__runInitializers(this, _email_extraInitializers), __runInitializers(this, _firstName_initializers, void 0));
        lastName = (__runInitializers(this, _firstName_extraInitializers), __runInitializers(this, _lastName_initializers, void 0));
        username = (__runInitializers(this, _lastName_extraInitializers), __runInitializers(this, _username_initializers, void 0));
        password = (__runInitializers(this, _username_extraInitializers), __runInitializers(this, _password_initializers, void 0));
        role = (__runInitializers(this, _password_extraInitializers), __runInitializers(this, _role_initializers, void 0));
        status = (__runInitializers(this, _role_extraInitializers), __runInitializers(this, _status_initializers, void 0));
        phone = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _phone_initializers, void 0));
        address = (__runInitializers(this, _phone_extraInitializers), __runInitializers(this, _address_initializers, void 0));
        city = (__runInitializers(this, _address_extraInitializers), __runInitializers(this, _city_initializers, void 0));
        country = (__runInitializers(this, _city_extraInitializers), __runInitializers(this, _country_initializers, void 0));
        bio = (__runInitializers(this, _country_extraInitializers), __runInitializers(this, _bio_initializers, void 0));
        skills = (__runInitializers(this, _bio_extraInitializers), __runInitializers(this, _skills_initializers, void 0));
        isEmailVerified = (__runInitializers(this, _skills_extraInitializers), __runInitializers(this, _isEmailVerified_initializers, void 0));
        isPhoneVerified = (__runInitializers(this, _isEmailVerified_extraInitializers), __runInitializers(this, _isPhoneVerified_initializers, void 0));
        isIdentityVerified = (__runInitializers(this, _isPhoneVerified_extraInitializers), __runInitializers(this, _isIdentityVerified_initializers, void 0));
        memberSince = (__runInitializers(this, _isIdentityVerified_extraInitializers), __runInitializers(this, _memberSince_initializers, void 0));
        providerProfile = (__runInitializers(this, _memberSince_extraInitializers), __runInitializers(this, _providerProfile_initializers, void 0));
        completedOrders = (__runInitializers(this, _providerProfile_extraInitializers), __runInitializers(this, _completedOrders_initializers, void 0));
        rating = (__runInitializers(this, _completedOrders_extraInitializers), __runInitializers(this, _rating_initializers, void 0));
        totalReviews = (__runInitializers(this, _rating_extraInitializers), __runInitializers(this, _totalReviews_initializers, void 0));
        paymentInfo = (__runInitializers(this, _totalReviews_extraInitializers), __runInitializers(this, _paymentInfo_initializers, void 0));
        notificationPreferences = (__runInitializers(this, _paymentInfo_extraInitializers), __runInitializers(this, _notificationPreferences_initializers, void 0));
        phoneNumber = (__runInitializers(this, _notificationPreferences_extraInitializers), __runInitializers(this, _phoneNumber_initializers, void 0));
        isTwoFactorEnabled = (__runInitializers(this, _phoneNumber_extraInitializers), __runInitializers(this, _isTwoFactorEnabled_initializers, void 0));
        twoFactorSecret = (__runInitializers(this, _isTwoFactorEnabled_extraInitializers), __runInitializers(this, _twoFactorSecret_initializers, void 0));
        avatar = (__runInitializers(this, _twoFactorSecret_extraInitializers), __runInitializers(this, _avatar_initializers, void 0));
        bioText = (__runInitializers(this, _avatar_extraInitializers), __runInitializers(this, _bioText_initializers, void 0));
        balance = (__runInitializers(this, _bioText_extraInitializers), __runInitializers(this, _balance_initializers, void 0));
        isFreelancer = (__runInitializers(this, _balance_extraInitializers), __runInitializers(this, _isFreelancer_initializers, void 0));
        isActive = (__runInitializers(this, _isFreelancer_extraInitializers), __runInitializers(this, _isActive_initializers, void 0));
        lastLogin = (__runInitializers(this, _isActive_extraInitializers), __runInitializers(this, _lastLogin_initializers, void 0));
        refreshToken = (__runInitializers(this, _lastLogin_extraInitializers), __runInitializers(this, _refreshToken_initializers, void 0));
        resetPasswordToken = (__runInitializers(this, _refreshToken_extraInitializers), __runInitializers(this, _resetPasswordToken_initializers, void 0));
        resetPasswordExpires = (__runInitializers(this, _resetPasswordToken_extraInitializers), __runInitializers(this, _resetPasswordExpires_initializers, void 0));
        emailVerificationToken = (__runInitializers(this, _resetPasswordExpires_extraInitializers), __runInitializers(this, _emailVerificationToken_initializers, void 0));
        services = (__runInitializers(this, _emailVerificationToken_extraInitializers), __runInitializers(this, _services_initializers, void 0));
        clientOrders = (__runInitializers(this, _services_extraInitializers), __runInitializers(this, _clientOrders_initializers, void 0));
        freelancerOrders = (__runInitializers(this, _clientOrders_extraInitializers), __runInitializers(this, _freelancerOrders_initializers, void 0));
        givenReviews = (__runInitializers(this, _freelancerOrders_extraInitializers), __runInitializers(this, _givenReviews_initializers, void 0));
        receivedReviews = (__runInitializers(this, _givenReviews_extraInitializers), __runInitializers(this, _receivedReviews_initializers, void 0));
        sentMessages = (__runInitializers(this, _receivedReviews_extraInitializers), __runInitializers(this, _sentMessages_initializers, void 0));
        receivedMessages = (__runInitializers(this, _sentMessages_extraInitializers), __runInitializers(this, _receivedMessages_initializers, void 0));
        following = (__runInitializers(this, _receivedMessages_extraInitializers), __runInitializers(this, _following_initializers, void 0));
        followers = (__runInitializers(this, _following_extraInitializers), __runInitializers(this, _followers_initializers, void 0));
        createdAt = (__runInitializers(this, _followers_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
        updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
        constructor(partial) {
            __runInitializers(this, _updatedAt_extraInitializers);
            Object.assign(this, partial);
        }
        get fullName() {
            return `${this.firstName} ${this.lastName}`;
        }
    };
    return User = _classThis;
})();
exports.User = User;
