version: '3.8'

services:
  # Service Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api

  # Service Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=3001
      - API_PREFIX=api
      - APP_URL=http://localhost:3001
      - FRONTEND_URL=http://localhost:3000
      # Base de données
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=nionfar
      - DB_SYNC=true
      # MongoDB
      - MONGODB_URI=mongodb://mongodb:27017/nionfar
      # JWT
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=1d
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret_key_here
      - JWT_REFRESH_EXPIRES_IN=7d
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # Service MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=nionfar
    restart: always

  # Service PostgreSQL
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nionfar

  # Service Redis pour le cache et les sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Service PgAdmin pour la gestion de la base de données
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@nionfar.sn
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Service Mongo Express pour gérer MongoDB via une interface web
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    restart: always

  # Service Mailhog pour le développement d'emails
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Interface web
      - "1025:1025" # SMTP

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
  mongodb_data: 